#!/bin/sh
set -a; [ -f /opt/ld/ai-configs-intro/app/.env ] && . /opt/ld/ai-configs-intro/app/.env; set +a

set -e

cd /opt/ld/ai-configs-intro/terraform/challenge-02
terraform apply -auto-approve

exit 0
