#!/bin/sh
set -a; [ -f /opt/ld/ai-configs-intro/app/.env ] && . /opt/ld/ai-configs-intro/app/.env; set +a

set -e

cd /opt/ld/ai-configs-intro/terraform/challenge-03
echo "project_key = \"${LD_PROJECT_KEY}\"" > terraform.tfvars
terraform init -input=false

exit 0
