#!/bin/sh
set -a; [ -f /opt/ld/ai-configs-intro/app/.env ] && . /opt/ld/ai-configs-intro/app/.env; set +a

set -e

cd /opt/ld/ai-configs-intro/terraform/challenge-01
terraform apply -auto-approve

python3 /opt/ld/ai-configs-intro/terraform/challenge-01/patch-server.py
service togglewear restart

exit 0
